"""empty message

Revision ID: 885bc02f74a6
Revises: 
Create Date: 2022-03-03 13:55:46.045250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885bc02f74a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('category', 'questions', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
